/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/post-scheduler': RouteRecordInfo<
      '/admin/post-scheduler',
      '/admin/post-scheduler',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/logout': RouteRecordInfo<
      '/auth/logout',
      '/auth/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community': RouteRecordInfo<
      '/community',
      '/community',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact': RouteRecordInfo<
      '/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/my-progress': RouteRecordInfo<
      '/my-progress',
      '/my-progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/api-best-practices-beginner': RouteRecordInfo<
      '/posts/api-best-practices-beginner',
      '/posts/api-best-practices-beginner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/backend-programming': RouteRecordInfo<
      '/posts/backend-programming',
      '/posts/backend-programming',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/build-first-web-page': RouteRecordInfo<
      '/posts/build-first-web-page',
      '/posts/build-first-web-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/design-to-code': RouteRecordInfo<
      '/posts/design-to-code',
      '/posts/design-to-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/dns-web-browsing': RouteRecordInfo<
      '/posts/dns-web-browsing',
      '/posts/dns-web-browsing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/docker-basics-guide-for-web-developers': RouteRecordInfo<
      '/posts/docker-basics-guide-for-web-developers',
      '/posts/docker-basics-guide-for-web-developers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git-basics': RouteRecordInfo<
      '/posts/git-basics',
      '/posts/git-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/internet-everywhere': RouteRecordInfo<
      '/posts/internet-everywhere',
      '/posts/internet-everywhere',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/javascript-basics': RouteRecordInfo<
      '/posts/javascript-basics',
      '/posts/javascript-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/modern-js-patterns': RouteRecordInfo<
      '/posts/modern-js-patterns',
      '/posts/modern-js-patterns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/responsive-design': RouteRecordInfo<
      '/posts/responsive-design',
      '/posts/responsive-design',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/web-performance-optimization': RouteRecordInfo<
      '/posts/web-performance-optimization',
      '/posts/web-performance-optimization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/web-security-essentials': RouteRecordInfo<
      '/posts/web-security-essentials',
      '/posts/web-security-essentials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/work-with-clients': RouteRecordInfo<
      '/posts/work-with-clients',
      '/posts/work-with-clients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/privacy': RouteRecordInfo<
      '/privacy',
      '/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/calculator': RouteRecordInfo<
      '/projects/calculator',
      '/projects/calculator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/card-components': RouteRecordInfo<
      '/projects/card-components',
      '/projects/card-components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/color-palette': RouteRecordInfo<
      '/projects/color-palette',
      '/projects/color-palette',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/color-switcher': RouteRecordInfo<
      '/projects/color-switcher',
      '/projects/color-switcher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/git-branch': RouteRecordInfo<
      '/projects/git-branch',
      '/projects/git-branch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/git-clone': RouteRecordInfo<
      '/projects/git-clone',
      '/projects/git-clone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/git-commit': RouteRecordInfo<
      '/projects/git-commit',
      '/projects/git-commit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/git-install': RouteRecordInfo<
      '/projects/git-install',
      '/projects/git-install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/git-merge': RouteRecordInfo<
      '/projects/git-merge',
      '/projects/git-merge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/git-remote': RouteRecordInfo<
      '/projects/git-remote',
      '/projects/git-remote',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/git-verify': RouteRecordInfo<
      '/projects/git-verify',
      '/projects/git-verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/grade-calculator': RouteRecordInfo<
      '/projects/grade-calculator',
      '/projects/grade-calculator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/hello-world': RouteRecordInfo<
      '/projects/hello-world',
      '/projects/hello-world',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/interactive-demo': RouteRecordInfo<
      '/projects/interactive-demo',
      '/projects/interactive-demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/number-game': RouteRecordInfo<
      '/projects/number-game',
      '/projects/number-game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/personal-profile': RouteRecordInfo<
      '/projects/personal-profile',
      '/projects/personal-profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/personal-profile-enhanced': RouteRecordInfo<
      '/projects/personal-profile-enhanced',
      '/projects/personal-profile-enhanced',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/photo-gallery': RouteRecordInfo<
      '/projects/photo-gallery',
      '/projects/photo-gallery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/photo-gallery-2': RouteRecordInfo<
      '/projects/photo-gallery-2',
      '/projects/photo-gallery-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/photo-gallery-enhanced': RouteRecordInfo<
      '/projects/photo-gallery-enhanced',
      '/projects/photo-gallery-enhanced',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/quiz-game': RouteRecordInfo<
      '/projects/quiz-game',
      '/projects/quiz-game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/recipe-page': RouteRecordInfo<
      '/projects/recipe-page',
      '/projects/recipe-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/selector-challenge': RouteRecordInfo<
      '/projects/selector-challenge',
      '/projects/selector-challenge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/temperature-converter': RouteRecordInfo<
      '/projects/temperature-converter',
      '/projects/temperature-converter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/todo-list': RouteRecordInfo<
      '/projects/todo-list',
      '/projects/todo-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/todo-list-2': RouteRecordInfo<
      '/projects/todo-list-2',
      '/projects/todo-list-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/todo-list-enhanced': RouteRecordInfo<
      '/projects/todo-list-enhanced',
      '/projects/todo-list-enhanced',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/terms': RouteRecordInfo<
      '/terms',
      '/terms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/the-graphite-journal': RouteRecordInfo<
      '/the-graphite-journal',
      '/the-graphite-journal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/': RouteRecordInfo<
      '/tutorials/',
      '/tutorials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/ai-assisted/': RouteRecordInfo<
      '/tutorials/ai-assisted/',
      '/tutorials/ai-assisted',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/ai-assisted/building-with-ai': RouteRecordInfo<
      '/tutorials/ai-assisted/building-with-ai',
      '/tutorials/ai-assisted/building-with-ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/ai-assisted/custom-gpt-automation': RouteRecordInfo<
      '/tutorials/ai-assisted/custom-gpt-automation',
      '/tutorials/ai-assisted/custom-gpt-automation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/ai-assisted/design-to-code': RouteRecordInfo<
      '/tutorials/ai-assisted/design-to-code',
      '/tutorials/ai-assisted/design-to-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/ai-assisted/introduction': RouteRecordInfo<
      '/tutorials/ai-assisted/introduction',
      '/tutorials/ai-assisted/introduction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/ai-assisted/projects/ai-component-docs': RouteRecordInfo<
      '/tutorials/ai-assisted/projects/ai-component-docs',
      '/tutorials/ai-assisted/projects/ai-component-docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/ai-assisted/projects/ai-landing-page': RouteRecordInfo<
      '/tutorials/ai-assisted/projects/ai-landing-page',
      '/tutorials/ai-assisted/projects/ai-landing-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/ai-assisted/projects/ai-rest-api-scaffold': RouteRecordInfo<
      '/tutorials/ai-assisted/projects/ai-rest-api-scaffold',
      '/tutorials/ai-assisted/projects/ai-rest-api-scaffold',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/ai-assisted/workflow-integration': RouteRecordInfo<
      '/tutorials/ai-assisted/workflow-integration',
      '/tutorials/ai-assisted/workflow-integration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/backend/': RouteRecordInfo<
      '/tutorials/backend/',
      '/tutorials/backend',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/backend/databases': RouteRecordInfo<
      '/tutorials/backend/databases',
      '/tutorials/backend/databases',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/backend/node-basics': RouteRecordInfo<
      '/tutorials/backend/node-basics',
      '/tutorials/backend/node-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/backend/rest-apis': RouteRecordInfo<
      '/tutorials/backend/rest-apis',
      '/tutorials/backend/rest-apis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner': RouteRecordInfo<
      '/tutorials/beginner',
      '/tutorials/beginner',
      Record<never, never>,
      Record<never, never>,
      | '/tutorials/beginner/css-basics/'
      | '/tutorials/beginner/css-basics/box-model'
      | '/tutorials/beginner/css-basics/colors'
      | '/tutorials/beginner/css-basics/flexbox'
      | '/tutorials/beginner/css-basics/introduction'
      | '/tutorials/beginner/css-basics/layout'
      | '/tutorials/beginner/css-basics/modern'
      | '/tutorials/beginner/css-basics/responsive'
      | '/tutorials/beginner/css-basics/selectors'
      | '/tutorials/beginner/css-basics/text'
      | '/tutorials/beginner/dom-basics/'
      | '/tutorials/beginner/dom-basics/arrays'
      | '/tutorials/beginner/dom-basics/dom-events'
      | '/tutorials/beginner/dom-basics/dom-manipulation'
      | '/tutorials/beginner/dom-basics/introduction'
      | '/tutorials/beginner/html-basics/'
      | '/tutorials/beginner/html-basics/html-doc-structure'
      | '/tutorials/beginner/html-basics/html-emmet'
      | '/tutorials/beginner/html-basics/html-first-page'
      | '/tutorials/beginner/html-basics/html-forms'
      | '/tutorials/beginner/html-basics/html-images'
      | '/tutorials/beginner/html-basics/html-links'
      | '/tutorials/beginner/html-basics/html-text'
      | '/tutorials/beginner/html-basics/introduction'
      | '/tutorials/beginner/javascript-basics/'
      | '/tutorials/beginner/javascript-basics/conditionals'
      | '/tutorials/beginner/javascript-basics/functions'
      | '/tutorials/beginner/javascript-basics/introduction'
      | '/tutorials/beginner/javascript-basics/loops'
      | '/tutorials/beginner/javascript-basics/operators'
      | '/tutorials/beginner/javascript-basics/variables-data-types'
    >,
    '/tutorials/beginner/css-basics/': RouteRecordInfo<
      '/tutorials/beginner/css-basics/',
      '/tutorials/beginner/css-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/css-basics/box-model': RouteRecordInfo<
      '/tutorials/beginner/css-basics/box-model',
      '/tutorials/beginner/css-basics/box-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/css-basics/colors': RouteRecordInfo<
      '/tutorials/beginner/css-basics/colors',
      '/tutorials/beginner/css-basics/colors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/css-basics/flexbox': RouteRecordInfo<
      '/tutorials/beginner/css-basics/flexbox',
      '/tutorials/beginner/css-basics/flexbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/css-basics/introduction': RouteRecordInfo<
      '/tutorials/beginner/css-basics/introduction',
      '/tutorials/beginner/css-basics/introduction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/css-basics/layout': RouteRecordInfo<
      '/tutorials/beginner/css-basics/layout',
      '/tutorials/beginner/css-basics/layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/css-basics/modern': RouteRecordInfo<
      '/tutorials/beginner/css-basics/modern',
      '/tutorials/beginner/css-basics/modern',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/css-basics/responsive': RouteRecordInfo<
      '/tutorials/beginner/css-basics/responsive',
      '/tutorials/beginner/css-basics/responsive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/css-basics/selectors': RouteRecordInfo<
      '/tutorials/beginner/css-basics/selectors',
      '/tutorials/beginner/css-basics/selectors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/css-basics/text': RouteRecordInfo<
      '/tutorials/beginner/css-basics/text',
      '/tutorials/beginner/css-basics/text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/dom-basics/': RouteRecordInfo<
      '/tutorials/beginner/dom-basics/',
      '/tutorials/beginner/dom-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/dom-basics/arrays': RouteRecordInfo<
      '/tutorials/beginner/dom-basics/arrays',
      '/tutorials/beginner/dom-basics/arrays',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/dom-basics/dom-events': RouteRecordInfo<
      '/tutorials/beginner/dom-basics/dom-events',
      '/tutorials/beginner/dom-basics/dom-events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/dom-basics/dom-manipulation': RouteRecordInfo<
      '/tutorials/beginner/dom-basics/dom-manipulation',
      '/tutorials/beginner/dom-basics/dom-manipulation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/dom-basics/introduction': RouteRecordInfo<
      '/tutorials/beginner/dom-basics/introduction',
      '/tutorials/beginner/dom-basics/introduction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/html-basics/': RouteRecordInfo<
      '/tutorials/beginner/html-basics/',
      '/tutorials/beginner/html-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/html-basics/html-doc-structure': RouteRecordInfo<
      '/tutorials/beginner/html-basics/html-doc-structure',
      '/tutorials/beginner/html-basics/html-doc-structure',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/html-basics/html-emmet': RouteRecordInfo<
      '/tutorials/beginner/html-basics/html-emmet',
      '/tutorials/beginner/html-basics/html-emmet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/html-basics/html-first-page': RouteRecordInfo<
      '/tutorials/beginner/html-basics/html-first-page',
      '/tutorials/beginner/html-basics/html-first-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/html-basics/html-forms': RouteRecordInfo<
      '/tutorials/beginner/html-basics/html-forms',
      '/tutorials/beginner/html-basics/html-forms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/html-basics/html-images': RouteRecordInfo<
      '/tutorials/beginner/html-basics/html-images',
      '/tutorials/beginner/html-basics/html-images',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/html-basics/html-links': RouteRecordInfo<
      '/tutorials/beginner/html-basics/html-links',
      '/tutorials/beginner/html-basics/html-links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/html-basics/html-text': RouteRecordInfo<
      '/tutorials/beginner/html-basics/html-text',
      '/tutorials/beginner/html-basics/html-text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/html-basics/introduction': RouteRecordInfo<
      '/tutorials/beginner/html-basics/introduction',
      '/tutorials/beginner/html-basics/introduction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/javascript-basics/': RouteRecordInfo<
      '/tutorials/beginner/javascript-basics/',
      '/tutorials/beginner/javascript-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/javascript-basics/conditionals': RouteRecordInfo<
      '/tutorials/beginner/javascript-basics/conditionals',
      '/tutorials/beginner/javascript-basics/conditionals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/javascript-basics/functions': RouteRecordInfo<
      '/tutorials/beginner/javascript-basics/functions',
      '/tutorials/beginner/javascript-basics/functions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/javascript-basics/introduction': RouteRecordInfo<
      '/tutorials/beginner/javascript-basics/introduction',
      '/tutorials/beginner/javascript-basics/introduction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/javascript-basics/loops': RouteRecordInfo<
      '/tutorials/beginner/javascript-basics/loops',
      '/tutorials/beginner/javascript-basics/loops',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/javascript-basics/operators': RouteRecordInfo<
      '/tutorials/beginner/javascript-basics/operators',
      '/tutorials/beginner/javascript-basics/operators',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/beginner/javascript-basics/variables-data-types': RouteRecordInfo<
      '/tutorials/beginner/javascript-basics/variables-data-types',
      '/tutorials/beginner/javascript-basics/variables-data-types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/capstone/': RouteRecordInfo<
      '/tutorials/capstone/',
      '/tutorials/capstone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/capstone/spec': RouteRecordInfo<
      '/tutorials/capstone/spec',
      '/tutorials/capstone/spec',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/deployments/': RouteRecordInfo<
      '/tutorials/deployments/',
      '/tutorials/deployments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/deployments/firebase-hosting': RouteRecordInfo<
      '/tutorials/deployments/firebase-hosting',
      '/tutorials/deployments/firebase-hosting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/deployments/static-vs-dynamic': RouteRecordInfo<
      '/tutorials/deployments/static-vs-dynamic',
      '/tutorials/deployments/static-vs-dynamic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/deployments/vercel-netlify': RouteRecordInfo<
      '/tutorials/deployments/vercel-netlify',
      '/tutorials/deployments/vercel-netlify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/getting-started/': RouteRecordInfo<
      '/tutorials/getting-started/',
      '/tutorials/getting-started',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/getting-started/browser-tools': RouteRecordInfo<
      '/tutorials/getting-started/browser-tools',
      '/tutorials/getting-started/browser-tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/getting-started/dev-environment': RouteRecordInfo<
      '/tutorials/getting-started/dev-environment',
      '/tutorials/getting-started/dev-environment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/getting-started/domain-hosting': RouteRecordInfo<
      '/tutorials/getting-started/domain-hosting',
      '/tutorials/getting-started/domain-hosting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/getting-started/how-internet-works': RouteRecordInfo<
      '/tutorials/getting-started/how-internet-works',
      '/tutorials/getting-started/how-internet-works',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/getting-started/text-editors': RouteRecordInfo<
      '/tutorials/getting-started/text-editors',
      '/tutorials/getting-started/text-editors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/getting-started/web-basics': RouteRecordInfo<
      '/tutorials/getting-started/web-basics',
      '/tutorials/getting-started/web-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/intermediate/git-basics/': RouteRecordInfo<
      '/tutorials/intermediate/git-basics/',
      '/tutorials/intermediate/git-basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/intermediate/git-basics/basic-commands': RouteRecordInfo<
      '/tutorials/intermediate/git-basics/basic-commands',
      '/tutorials/intermediate/git-basics/basic-commands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/intermediate/git-basics/branching': RouteRecordInfo<
      '/tutorials/intermediate/git-basics/branching',
      '/tutorials/intermediate/git-basics/branching',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/intermediate/git-basics/conclusion': RouteRecordInfo<
      '/tutorials/intermediate/git-basics/conclusion',
      '/tutorials/intermediate/git-basics/conclusion',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/intermediate/git-basics/installation': RouteRecordInfo<
      '/tutorials/intermediate/git-basics/installation',
      '/tutorials/intermediate/git-basics/installation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/intermediate/git-basics/introduction': RouteRecordInfo<
      '/tutorials/intermediate/git-basics/introduction',
      '/tutorials/intermediate/git-basics/introduction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/intermediate/git-basics/merging': RouteRecordInfo<
      '/tutorials/intermediate/git-basics/merging',
      '/tutorials/intermediate/git-basics/merging',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/intermediate/git-basics/remote-repositories': RouteRecordInfo<
      '/tutorials/intermediate/git-basics/remote-repositories',
      '/tutorials/intermediate/git-basics/remote-repositories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/intermediate/git-basics/workflow': RouteRecordInfo<
      '/tutorials/intermediate/git-basics/workflow',
      '/tutorials/intermediate/git-basics/workflow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/practice': RouteRecordInfo<
      '/tutorials/practice',
      '/tutorials/practice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/seo-analytics/': RouteRecordInfo<
      '/tutorials/seo-analytics/',
      '/tutorials/seo-analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/seo-analytics/analytics-setup': RouteRecordInfo<
      '/tutorials/seo-analytics/analytics-setup',
      '/tutorials/seo-analytics/analytics-setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tutorials/seo-analytics/on-page-seo': RouteRecordInfo<
      '/tutorials/seo-analytics/on-page-seo',
      '/tutorials/seo-analytics/on-page-seo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/404.vue': {
      routes:
        | '/404'
      views:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/admin/post-scheduler.vue': {
      routes:
        | '/admin/post-scheduler'
      views:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/auth/logout.vue': {
      routes:
        | '/auth/logout'
      views:
        | never
    }
    'src/pages/auth/register.vue': {
      routes:
        | '/auth/register'
      views:
        | never
    }
    'src/pages/community.vue': {
      routes:
        | '/community'
      views:
        | never
    }
    'src/pages/contact.vue': {
      routes:
        | '/contact'
      views:
        | never
    }
    'src/pages/my-progress.vue': {
      routes:
        | '/my-progress'
      views:
        | never
    }
    'src/pages/posts/api-best-practices-beginner.vue': {
      routes:
        | '/posts/api-best-practices-beginner'
      views:
        | never
    }
    'src/pages/posts/backend-programming.vue': {
      routes:
        | '/posts/backend-programming'
      views:
        | never
    }
    'src/pages/posts/build-first-web-page.vue': {
      routes:
        | '/posts/build-first-web-page'
      views:
        | never
    }
    'src/pages/posts/design-to-code.vue': {
      routes:
        | '/posts/design-to-code'
      views:
        | never
    }
    'src/pages/posts/dns-web-browsing.vue': {
      routes:
        | '/posts/dns-web-browsing'
      views:
        | never
    }
    'src/pages/posts/docker-basics-guide-for-web-developers.vue': {
      routes:
        | '/posts/docker-basics-guide-for-web-developers'
      views:
        | never
    }
    'src/pages/posts/git-basics.vue': {
      routes:
        | '/posts/git-basics'
      views:
        | never
    }
    'src/pages/posts/internet-everywhere.vue': {
      routes:
        | '/posts/internet-everywhere'
      views:
        | never
    }
    'src/pages/posts/javascript-basics.vue': {
      routes:
        | '/posts/javascript-basics'
      views:
        | never
    }
    'src/pages/posts/modern-js-patterns.vue': {
      routes:
        | '/posts/modern-js-patterns'
      views:
        | never
    }
    'src/pages/posts/responsive-design.vue': {
      routes:
        | '/posts/responsive-design'
      views:
        | never
    }
    'src/pages/posts/web-performance-optimization.vue': {
      routes:
        | '/posts/web-performance-optimization'
      views:
        | never
    }
    'src/pages/posts/web-security-essentials.vue': {
      routes:
        | '/posts/web-security-essentials'
      views:
        | never
    }
    'src/pages/posts/work-with-clients.vue': {
      routes:
        | '/posts/work-with-clients'
      views:
        | never
    }
    'src/pages/privacy.vue': {
      routes:
        | '/privacy'
      views:
        | never
    }
    'src/pages/projects/index.vue': {
      routes:
        | '/projects/'
      views:
        | never
    }
    'src/pages/projects/calculator.vue': {
      routes:
        | '/projects/calculator'
      views:
        | never
    }
    'src/pages/projects/card-components.vue': {
      routes:
        | '/projects/card-components'
      views:
        | never
    }
    'src/pages/projects/color-palette.vue': {
      routes:
        | '/projects/color-palette'
      views:
        | never
    }
    'src/pages/projects/color-switcher.vue': {
      routes:
        | '/projects/color-switcher'
      views:
        | never
    }
    'src/pages/projects/git-branch.vue': {
      routes:
        | '/projects/git-branch'
      views:
        | never
    }
    'src/pages/projects/git-clone.vue': {
      routes:
        | '/projects/git-clone'
      views:
        | never
    }
    'src/pages/projects/git-commit.vue': {
      routes:
        | '/projects/git-commit'
      views:
        | never
    }
    'src/pages/projects/git-install.vue': {
      routes:
        | '/projects/git-install'
      views:
        | never
    }
    'src/pages/projects/git-merge.vue': {
      routes:
        | '/projects/git-merge'
      views:
        | never
    }
    'src/pages/projects/git-remote.vue': {
      routes:
        | '/projects/git-remote'
      views:
        | never
    }
    'src/pages/projects/git-verify.vue': {
      routes:
        | '/projects/git-verify'
      views:
        | never
    }
    'src/pages/projects/grade-calculator.vue': {
      routes:
        | '/projects/grade-calculator'
      views:
        | never
    }
    'src/pages/projects/hello-world.vue': {
      routes:
        | '/projects/hello-world'
      views:
        | never
    }
    'src/pages/projects/interactive-demo.vue': {
      routes:
        | '/projects/interactive-demo'
      views:
        | never
    }
    'src/pages/projects/number-game.vue': {
      routes:
        | '/projects/number-game'
      views:
        | never
    }
    'src/pages/projects/personal-profile.vue': {
      routes:
        | '/projects/personal-profile'
      views:
        | never
    }
    'src/pages/projects/personal-profile-enhanced.vue': {
      routes:
        | '/projects/personal-profile-enhanced'
      views:
        | never
    }
    'src/pages/projects/photo-gallery.vue': {
      routes:
        | '/projects/photo-gallery'
      views:
        | never
    }
    'src/pages/projects/photo-gallery-2.vue': {
      routes:
        | '/projects/photo-gallery-2'
      views:
        | never
    }
    'src/pages/projects/photo-gallery-enhanced.vue': {
      routes:
        | '/projects/photo-gallery-enhanced'
      views:
        | never
    }
    'src/pages/projects/quiz-game.vue': {
      routes:
        | '/projects/quiz-game'
      views:
        | never
    }
    'src/pages/projects/recipe-page.vue': {
      routes:
        | '/projects/recipe-page'
      views:
        | never
    }
    'src/pages/projects/selector-challenge.vue': {
      routes:
        | '/projects/selector-challenge'
      views:
        | never
    }
    'src/pages/projects/temperature-converter.vue': {
      routes:
        | '/projects/temperature-converter'
      views:
        | never
    }
    'src/pages/projects/todo-list.vue': {
      routes:
        | '/projects/todo-list'
      views:
        | never
    }
    'src/pages/projects/todo-list-2.vue': {
      routes:
        | '/projects/todo-list-2'
      views:
        | never
    }
    'src/pages/projects/todo-list-enhanced.vue': {
      routes:
        | '/projects/todo-list-enhanced'
      views:
        | never
    }
    'src/pages/terms.vue': {
      routes:
        | '/terms'
      views:
        | never
    }
    'src/pages/the-graphite-journal.vue': {
      routes:
        | '/the-graphite-journal'
      views:
        | never
    }
    'src/pages/tutorials/index.vue': {
      routes:
        | '/tutorials/'
      views:
        | never
    }
    'src/pages/tutorials/ai-assisted/index.vue': {
      routes:
        | '/tutorials/ai-assisted/'
      views:
        | never
    }
    'src/pages/tutorials/ai-assisted/building-with-ai.vue': {
      routes:
        | '/tutorials/ai-assisted/building-with-ai'
      views:
        | never
    }
    'src/pages/tutorials/ai-assisted/custom-gpt-automation.vue': {
      routes:
        | '/tutorials/ai-assisted/custom-gpt-automation'
      views:
        | never
    }
    'src/pages/tutorials/ai-assisted/design-to-code.vue': {
      routes:
        | '/tutorials/ai-assisted/design-to-code'
      views:
        | never
    }
    'src/pages/tutorials/ai-assisted/introduction.vue': {
      routes:
        | '/tutorials/ai-assisted/introduction'
      views:
        | never
    }
    'src/pages/tutorials/ai-assisted/projects/ai-component-docs.vue': {
      routes:
        | '/tutorials/ai-assisted/projects/ai-component-docs'
      views:
        | never
    }
    'src/pages/tutorials/ai-assisted/projects/ai-landing-page.vue': {
      routes:
        | '/tutorials/ai-assisted/projects/ai-landing-page'
      views:
        | never
    }
    'src/pages/tutorials/ai-assisted/projects/ai-rest-api-scaffold.vue': {
      routes:
        | '/tutorials/ai-assisted/projects/ai-rest-api-scaffold'
      views:
        | never
    }
    'src/pages/tutorials/ai-assisted/workflow-integration.vue': {
      routes:
        | '/tutorials/ai-assisted/workflow-integration'
      views:
        | never
    }
    'src/pages/tutorials/backend/index.vue': {
      routes:
        | '/tutorials/backend/'
      views:
        | never
    }
    'src/pages/tutorials/backend/databases.vue': {
      routes:
        | '/tutorials/backend/databases'
      views:
        | never
    }
    'src/pages/tutorials/backend/node-basics.vue': {
      routes:
        | '/tutorials/backend/node-basics'
      views:
        | never
    }
    'src/pages/tutorials/backend/rest-apis.vue': {
      routes:
        | '/tutorials/backend/rest-apis'
      views:
        | never
    }
    'src/pages/tutorials/beginner.vue': {
      routes:
        | '/tutorials/beginner'
        | '/tutorials/beginner/css-basics/'
        | '/tutorials/beginner/css-basics/box-model'
        | '/tutorials/beginner/css-basics/colors'
        | '/tutorials/beginner/css-basics/flexbox'
        | '/tutorials/beginner/css-basics/introduction'
        | '/tutorials/beginner/css-basics/layout'
        | '/tutorials/beginner/css-basics/modern'
        | '/tutorials/beginner/css-basics/responsive'
        | '/tutorials/beginner/css-basics/selectors'
        | '/tutorials/beginner/css-basics/text'
        | '/tutorials/beginner/dom-basics/'
        | '/tutorials/beginner/dom-basics/arrays'
        | '/tutorials/beginner/dom-basics/dom-events'
        | '/tutorials/beginner/dom-basics/dom-manipulation'
        | '/tutorials/beginner/dom-basics/introduction'
        | '/tutorials/beginner/html-basics/'
        | '/tutorials/beginner/html-basics/html-doc-structure'
        | '/tutorials/beginner/html-basics/html-emmet'
        | '/tutorials/beginner/html-basics/html-first-page'
        | '/tutorials/beginner/html-basics/html-forms'
        | '/tutorials/beginner/html-basics/html-images'
        | '/tutorials/beginner/html-basics/html-links'
        | '/tutorials/beginner/html-basics/html-text'
        | '/tutorials/beginner/html-basics/introduction'
        | '/tutorials/beginner/javascript-basics/'
        | '/tutorials/beginner/javascript-basics/conditionals'
        | '/tutorials/beginner/javascript-basics/functions'
        | '/tutorials/beginner/javascript-basics/introduction'
        | '/tutorials/beginner/javascript-basics/loops'
        | '/tutorials/beginner/javascript-basics/operators'
        | '/tutorials/beginner/javascript-basics/variables-data-types'
      views:
        | 'default'
    }
    'src/pages/tutorials/beginner/css-basics/index.vue': {
      routes:
        | '/tutorials/beginner/css-basics/'
      views:
        | never
    }
    'src/pages/tutorials/beginner/css-basics/box-model.vue': {
      routes:
        | '/tutorials/beginner/css-basics/box-model'
      views:
        | never
    }
    'src/pages/tutorials/beginner/css-basics/colors.vue': {
      routes:
        | '/tutorials/beginner/css-basics/colors'
      views:
        | never
    }
    'src/pages/tutorials/beginner/css-basics/flexbox.vue': {
      routes:
        | '/tutorials/beginner/css-basics/flexbox'
      views:
        | never
    }
    'src/pages/tutorials/beginner/css-basics/introduction.vue': {
      routes:
        | '/tutorials/beginner/css-basics/introduction'
      views:
        | never
    }
    'src/pages/tutorials/beginner/css-basics/layout.vue': {
      routes:
        | '/tutorials/beginner/css-basics/layout'
      views:
        | never
    }
    'src/pages/tutorials/beginner/css-basics/modern.vue': {
      routes:
        | '/tutorials/beginner/css-basics/modern'
      views:
        | never
    }
    'src/pages/tutorials/beginner/css-basics/responsive.vue': {
      routes:
        | '/tutorials/beginner/css-basics/responsive'
      views:
        | never
    }
    'src/pages/tutorials/beginner/css-basics/selectors.vue': {
      routes:
        | '/tutorials/beginner/css-basics/selectors'
      views:
        | never
    }
    'src/pages/tutorials/beginner/css-basics/text.vue': {
      routes:
        | '/tutorials/beginner/css-basics/text'
      views:
        | never
    }
    'src/pages/tutorials/beginner/dom-basics/index.vue': {
      routes:
        | '/tutorials/beginner/dom-basics/'
      views:
        | never
    }
    'src/pages/tutorials/beginner/dom-basics/arrays.vue': {
      routes:
        | '/tutorials/beginner/dom-basics/arrays'
      views:
        | never
    }
    'src/pages/tutorials/beginner/dom-basics/dom-events.vue': {
      routes:
        | '/tutorials/beginner/dom-basics/dom-events'
      views:
        | never
    }
    'src/pages/tutorials/beginner/dom-basics/dom-manipulation.vue': {
      routes:
        | '/tutorials/beginner/dom-basics/dom-manipulation'
      views:
        | never
    }
    'src/pages/tutorials/beginner/dom-basics/introduction.vue': {
      routes:
        | '/tutorials/beginner/dom-basics/introduction'
      views:
        | never
    }
    'src/pages/tutorials/beginner/html-basics/index.vue': {
      routes:
        | '/tutorials/beginner/html-basics/'
      views:
        | never
    }
    'src/pages/tutorials/beginner/html-basics/html-doc-structure.vue': {
      routes:
        | '/tutorials/beginner/html-basics/html-doc-structure'
      views:
        | never
    }
    'src/pages/tutorials/beginner/html-basics/html-emmet.vue': {
      routes:
        | '/tutorials/beginner/html-basics/html-emmet'
      views:
        | never
    }
    'src/pages/tutorials/beginner/html-basics/html-first-page.vue': {
      routes:
        | '/tutorials/beginner/html-basics/html-first-page'
      views:
        | never
    }
    'src/pages/tutorials/beginner/html-basics/html-forms.vue': {
      routes:
        | '/tutorials/beginner/html-basics/html-forms'
      views:
        | never
    }
    'src/pages/tutorials/beginner/html-basics/html-images.vue': {
      routes:
        | '/tutorials/beginner/html-basics/html-images'
      views:
        | never
    }
    'src/pages/tutorials/beginner/html-basics/html-links.vue': {
      routes:
        | '/tutorials/beginner/html-basics/html-links'
      views:
        | never
    }
    'src/pages/tutorials/beginner/html-basics/html-text.vue': {
      routes:
        | '/tutorials/beginner/html-basics/html-text'
      views:
        | never
    }
    'src/pages/tutorials/beginner/html-basics/introduction.vue': {
      routes:
        | '/tutorials/beginner/html-basics/introduction'
      views:
        | never
    }
    'src/pages/tutorials/beginner/javascript-basics/index.vue': {
      routes:
        | '/tutorials/beginner/javascript-basics/'
      views:
        | never
    }
    'src/pages/tutorials/beginner/javascript-basics/conditionals.vue': {
      routes:
        | '/tutorials/beginner/javascript-basics/conditionals'
      views:
        | never
    }
    'src/pages/tutorials/beginner/javascript-basics/functions.vue': {
      routes:
        | '/tutorials/beginner/javascript-basics/functions'
      views:
        | never
    }
    'src/pages/tutorials/beginner/javascript-basics/introduction.vue': {
      routes:
        | '/tutorials/beginner/javascript-basics/introduction'
      views:
        | never
    }
    'src/pages/tutorials/beginner/javascript-basics/loops.vue': {
      routes:
        | '/tutorials/beginner/javascript-basics/loops'
      views:
        | never
    }
    'src/pages/tutorials/beginner/javascript-basics/operators.vue': {
      routes:
        | '/tutorials/beginner/javascript-basics/operators'
      views:
        | never
    }
    'src/pages/tutorials/beginner/javascript-basics/variables-data-types.vue': {
      routes:
        | '/tutorials/beginner/javascript-basics/variables-data-types'
      views:
        | never
    }
    'src/pages/tutorials/capstone/index.vue': {
      routes:
        | '/tutorials/capstone/'
      views:
        | never
    }
    'src/pages/tutorials/capstone/spec.vue': {
      routes:
        | '/tutorials/capstone/spec'
      views:
        | never
    }
    'src/pages/tutorials/deployments/index.vue': {
      routes:
        | '/tutorials/deployments/'
      views:
        | never
    }
    'src/pages/tutorials/deployments/firebase-hosting.vue': {
      routes:
        | '/tutorials/deployments/firebase-hosting'
      views:
        | never
    }
    'src/pages/tutorials/deployments/static-vs-dynamic.vue': {
      routes:
        | '/tutorials/deployments/static-vs-dynamic'
      views:
        | never
    }
    'src/pages/tutorials/deployments/vercel-netlify.vue': {
      routes:
        | '/tutorials/deployments/vercel-netlify'
      views:
        | never
    }
    'src/pages/tutorials/getting-started/index.vue': {
      routes:
        | '/tutorials/getting-started/'
      views:
        | never
    }
    'src/pages/tutorials/getting-started/browser-tools.vue': {
      routes:
        | '/tutorials/getting-started/browser-tools'
      views:
        | never
    }
    'src/pages/tutorials/getting-started/dev-environment.vue': {
      routes:
        | '/tutorials/getting-started/dev-environment'
      views:
        | never
    }
    'src/pages/tutorials/getting-started/domain-hosting.vue': {
      routes:
        | '/tutorials/getting-started/domain-hosting'
      views:
        | never
    }
    'src/pages/tutorials/getting-started/how-internet-works.vue': {
      routes:
        | '/tutorials/getting-started/how-internet-works'
      views:
        | never
    }
    'src/pages/tutorials/getting-started/text-editors.vue': {
      routes:
        | '/tutorials/getting-started/text-editors'
      views:
        | never
    }
    'src/pages/tutorials/getting-started/web-basics.vue': {
      routes:
        | '/tutorials/getting-started/web-basics'
      views:
        | never
    }
    'src/pages/tutorials/intermediate/git-basics/index.vue': {
      routes:
        | '/tutorials/intermediate/git-basics/'
      views:
        | never
    }
    'src/pages/tutorials/intermediate/git-basics/basic-commands.vue': {
      routes:
        | '/tutorials/intermediate/git-basics/basic-commands'
      views:
        | never
    }
    'src/pages/tutorials/intermediate/git-basics/branching.vue': {
      routes:
        | '/tutorials/intermediate/git-basics/branching'
      views:
        | never
    }
    'src/pages/tutorials/intermediate/git-basics/conclusion.vue': {
      routes:
        | '/tutorials/intermediate/git-basics/conclusion'
      views:
        | never
    }
    'src/pages/tutorials/intermediate/git-basics/installation.vue': {
      routes:
        | '/tutorials/intermediate/git-basics/installation'
      views:
        | never
    }
    'src/pages/tutorials/intermediate/git-basics/introduction.vue': {
      routes:
        | '/tutorials/intermediate/git-basics/introduction'
      views:
        | never
    }
    'src/pages/tutorials/intermediate/git-basics/merging.vue': {
      routes:
        | '/tutorials/intermediate/git-basics/merging'
      views:
        | never
    }
    'src/pages/tutorials/intermediate/git-basics/remote-repositories.vue': {
      routes:
        | '/tutorials/intermediate/git-basics/remote-repositories'
      views:
        | never
    }
    'src/pages/tutorials/intermediate/git-basics/workflow.vue': {
      routes:
        | '/tutorials/intermediate/git-basics/workflow'
      views:
        | never
    }
    'src/pages/tutorials/practice.vue': {
      routes:
        | '/tutorials/practice'
      views:
        | never
    }
    'src/pages/tutorials/seo-analytics/index.vue': {
      routes:
        | '/tutorials/seo-analytics/'
      views:
        | never
    }
    'src/pages/tutorials/seo-analytics/analytics-setup.vue': {
      routes:
        | '/tutorials/seo-analytics/analytics-setup'
      views:
        | never
    }
    'src/pages/tutorials/seo-analytics/on-page-seo.vue': {
      routes:
        | '/tutorials/seo-analytics/on-page-seo'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
